version: '3.7'
services:
  myDB:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - ./db_data:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=db_app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080